version: "3"
services:
  flaskapp:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: fastapi-backend
    restart: always
    ports:
      - "8000:8000"
    volumes:
      - .:/app